import 'package:flutter/material.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/DonePost.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/Edit%20History.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditAddress.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditEmail.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditName.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditPassword.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditProfilePic.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/HomepageStaff.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/PostFood.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/Profile.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/RealtimeUpdate.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/RealtimeUpdate2.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/ViewReviewAndRating.dart';
import 'package:usm_foodsaver/Membership System Module/CreateRestaurantProfile.dart';
import 'package:usm_foodsaver/Membership System Module/CreateUserProfile.dart';
import 'package:usm_foodsaver/Membership System Module/CustomerService.dart';
import 'package:usm_foodsaver/Membership System Module/DuitNowScan.dart';
import 'package:usm_foodsaver/Membership%20System%20Module/HomePage.dart';
import 'package:usm_foodsaver/Membership System Module/Login.dart';
import 'package:usm_foodsaver/Membership System Module/LoginFail.dart';
import 'package:usm_foodsaver/Membership System Module/NormalProfile.dart';
import 'package:usm_foodsaver/Membership System Module/PaymentMethod.dart';
import 'package:usm_foodsaver/Membership System Module/PremiumPlan.dart';
import 'package:usm_foodsaver/Membership System Module/PremiumPrice.dart';
import 'package:usm_foodsaver/Membership System Module/PremiumProfile.dart';
import 'package:usm_foodsaver/Membership System Module/PrivacyPolicy.dart';
import 'package:usm_foodsaver/Membership System Module/RestaurantAddress.dart';
import 'package:usm_foodsaver/Membership System Module/RestaurantName.dart';
import 'package:usm_foodsaver/Membership System Module/RestaurantPic.dart';
import 'package:usm_foodsaver/Membership System Module/RestaurantProfile.dart';
import 'package:usm_foodsaver/Membership System Module/SignUp.dart';
import 'package:usm_foodsaver/Membership System Module/StaffLogin.dart';
import 'package:usm_foodsaver/Membership System Module/StaffSignUp.dart';
import 'package:usm_foodsaver/Membership System Module/StudentLogin.dart';
import 'package:usm_foodsaver/Membership System Module/StudentSignUp.dart';
import 'package:usm_foodsaver/Membership System Module/Successful.dart';
import 'package:usm_foodsaver/Membership System Module/TermsofService.dart';
import 'package:usm_foodsaver/Membership System Module/tngScan.dart';
import 'package:usm_foodsaver/Membership System Module/UploadSS.dart';
import 'package:usm_foodsaver/Membership System Module/UploadUserPhoto.dart';
import 'package:usm_foodsaver/Membership%20System%20Module/HomePage.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomePage(),
          //Premiumprofile(),
          //Normalprofile(),
          //Createuserprofile(),
        ]),
      ),
    );
  }
}