import 'package:flutter/material.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/DonePost.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/Edit%20History.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditAddress.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditEmail.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditName.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditPassword.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/EditProfilePic.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/HomepageStaff.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/PostFood.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/Profile.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/RealtimeUpdate.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/RealtimeUpdate2.dart';
import 'package:usm_foodsaver/Food%20Management%20Module/ViewReviewAndRating.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomepageStaff(),
        ]),
      ),
    );
  }
}